#config file in yaml format for the IPF pipeline
#
#
#we need to start with the vcf files input for the phasing step
#config file in yaml format for the IPF pipeline
#
#
cohort_name: "Sample_POP" #study population name
pop_group: "Pop_group" #population ancestry [can be one of EUR, AFR, ASN, EAS, SAS]
ref_panel: "ref_pane_name" #name of the reference panel. Can be one of [IGRP, TGP3, ....]

chromosomes: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23] #cromosomes to work with

# genetic_map_chr: "/netapp/nfs/resources/1000GP_phase3/impute/"
paths:
  input_folder: "input_folder" #base folder containing input data
  input_file_prefix: "input file prefix" #this is the prefix with the complete path of the PLINK file to be used.
  output_folder: "output_folder" #base folder for output
  log_folder: "log_folder" #base folder for output
  genetic_map_path: "/netapp/nfs/resources/1000GP_phase3/impute/" #path containing genetic maps
  ref_panel_base_folder: "ref_panel_base_dir" #folder path containing reference panel files
  allele_recode_file: "allele_recode_file" #folder path containing an allele recode file
  snp_array_update_allele_file: "snp_array_update_allele_file" #absolute path containing the update allele file specific for the snp array used

rules:
  impute:
    k_hap: 10000
    ne : 20000
    iter: 60
    burnin: 20
    buffer_size: 250
    chunk_size: 3000000
    options: '-allow_large_regions -use_prephased_g -o_gz'
    mem: 15000 #default to 15Gb
    threads: 1 #in impute2 his parameter is not used, maybe in following versions
  indelsRemove:
  plinkSplit:
  snpCheck:
  snpFlipFile:
  snpFlip:
  allFix:
  plink2vcf:
  phase:
    mcmc_iterations: '10b,1p,1b,1p,1b,1p,1b,1p,10m' #maxed out parameteres according to SHAPEIT4 manual. Default setting are : 5b,1p,1b,1p,1b,1p,5m
    pbwt_depth: 8 #maxed out parameteres according to SHAPEIT4 manual. Default setting are : 4

tools:
  shapeit: "/share/apps/bio/bin/shapeit"
  phasing_tool: "shapeit4_path"
  impute: "impute_path"
  plink: "plink_path"