#config file in yaml format for the IPF pipeline
#
#
#we need to start with the vcf files input for the phasing step
#config file in yaml format for the IPF pipeline
#
#
cohort_name: "Sample_POP" #study population name
pop_group: "Pop_group" #population ancestry [can be one of EUR, AFR, ASN, EAS, SAS]
ref_panel: "ref_pane_name" #name of the reference panel. Can be one of [IGRP, TGP3, ....]

chr: "sample_chrom" #cromosome to work with

# genetic_map_chr: "/netapp/nfs/resources/1000GP_phase3/impute/"
paths:
  input_folder: "input_folder" #base folder containing input data
  input_file_prefix: "input file prefix" #this is the prefix with the complete path of the PLINK file to be used.
  output_folder: "output_folder" #base folder for output
  log_folder: "log_folder" #base folder for output
  genetic_map_path: "/netapp/nfs/resources/1000GP_phase3/impute/" #path containing genetic maps
  ref_panel_base_folder: "ref_panel_base_dir" #folder path containing reference panel files


tools:
  shapeit: "/share/apps/bio/bin/shapeit"
  impute: "impute_path"
  plink: "plink_path"