#config file in yaml format for the IPF pipeline
#
#
#we need to start with the vcf files input for the phasing step
#config file in yaml format for the IPF pipeline
#
#
cohort_name: "Sample_POP" #study population name
pop_group: "Pop_group" #population ancestry [can be one of EUR, AFR, ASN, EAS, SAS]
ref_panel: "ref_pane_name" #name of the reference panel. Can be one of [IGRPv1, TGP3, ....]

chromosomes: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23] #cromosomes to work with

# genetic_map_chr: "/netapp/nfs/resources/1000GP_phase3/impute/"
paths:
  input_folder: "input_folder" #base folder containing input data
  input_file_prefix: "input file prefix" #this is the prefix with the complete path of the PLINK file to be used.
  output_folder: "output_folder" #base folder for output
  log_folder: "log_folder" #base folder for output
  genetic_map_path: "/netapp/nfs/resources/gen_map/shapeit4" #path containing genetic maps for IMPUTATION and PHASING (SHAPEIT4 and IMPUTE5 version)
  ref_panel_base_folder: "/shared/resources/references/VCF" #folder path containing reference panel files
  allele_recode_file: "/netapp/nfs/resources/dbSNP/human_9606_b154_GRCh37p13/GCF_000001405.25.SNPS.dbSNP154.tab" #folder path containing an allele recode file
  ext_ref_annot_file: "/netapp/nfs/resources/dbSNP/human_9606_b154_GRCh37p13/GCF_000001405.25.vcf.gz" #external reference file to perform annotation on VCF files
  ref_fasta: "/shared/resources/hgRef/hg19/hg19_nochr.fasta" #reference fasta file
  snp_array_update_allele_file: "snp_array_update_allele_file" #absolute path containing the update allele file specific for the snp array used
  scripts: "scripts_folder_path" #folder containing scripts needed in the workflo

rules:
  chunkGenerator:
    window-size: 5000000
    window-count: 3000
  impute:
    # k_hap: 10000
    ne : 20000
    pbwt_depth: 8
    # iter: 60
    # burnin: 20
    buffer_size: 250
    # chunk_size: 3000000
    options: '--out-gp-field'
    mem: 15000 #default to 15Gb
    threads: 4 #in impute2 his parameter is not used, maybe in following versions
  concatImputed:
    temp: "temp folder path" #in case we need to sort the concatenated vcf files 
  indelsRemove:
  plinkSplit:
  snpCheck:
    ref_panel_base_folder: "ref_panel_base_dir" #shapeit2 ref panel format path for this rule ONLY
    genetic_map_path: "/netapp/nfs/resources/1000GP_phase3/impute" #shapeit2 genetic map format path, to be used in this rule ONLY
  chrXSplit:
    args: "hg19 'no-fail'"
  snpFlip:
  allFix:
  plink2vcf:
    chr_rename: "support_files/rename_chr_hg19.txt" #refer here to the correct file to be used to rename chromosmes based on the reference genome build used
  vcfFixRef:
    temp: "temp folder path" #in case we need to sort the concatenated vcf files 
  phaseShapeit:
    mcmc_iterations: "--mcmc-iterations 10b,1p,1b,1p,1b,1p,1b,1p,10m" #maxed out parameteres according to SHAPEIT4 manual. Default setting are : 5b,1p,1b,1p,1b,1p,5m
    pbwt_depth: "--pbwt-depth 8" #maxed out parameteres according to SHAPEIT4 manual. Default setting are : 4
    additional_args: ""
  phase: #the following parameters are for the phasing rule using Eagle only
    mem: 50000 #default to 50Gb
    genetic_map: "/home/cocca/softwares/eagle/Eagle_v2.4.1/tables/genetic_map_hg19_withX.txt.gz"
    additional_args: "--vcfOutFormat z --noImpMissing"
  

tools:
  shapeit: "/share/apps/bio/bin/shapeit"
  phasing_tool: "shapeit4_path"
  impute: "impute_path"
  chunker_tool: "chunker_path"
  plink: "plink_path"
  bcftools: "bcftools_path"